apiVersion: v1 
kind: Pod
metadata:
  name: nginxpod
  namespace: roboshop
spec:
  containers:
  - name: nginx
    image:  nginx
    imagePullPolicy: Always
    ports:  
    - containerPort: 80
  - name: almalinux
    image: almalinux
    command: ["sleep","2000"]