apiVersion: v1 
kind: Pod
metadata:
  name: stresspod
spec:
  containers:
    - name: stress
      image: udaysha10/stresscntr
      command: ["sleep","2000"]
      resources:
        requests:
          memory: ""250Mi"
          cpu: ""250m"
        limits:
          memory: ""500Mi"
          cpu: ""500m"